Repository pjainxido/jaranda_pentagon, pull requests merged in 2021-08, with the labels that each got.

#7 [CHORE] #2 - firebase 기본 셋업
  .gitignore
  package.json
  src/firebase.js
  yarn.lock
Labels: chore

#9 Feat/2/firebase setup
  src/api/user/index.js
  src/firebase.js
Labels: feature

#10 [FEAT] GNB 레이아웃 구현
  public/image/jaranda.log.png
  src/App.js
  src/components/Nav.js
Labels: feature

#13 [FEAT] 로그인 레이아웃 구현
  src/pages/Login/Login.js
Labels: feature

#15 api 추가 제작
  package.json
  src/api/menu/index.js
  src/api/role/index.js
  src/api/user/index.js
  yarn.lock
Labels: feature

#19 findUserByIdAndPassword api 제작
  src/api/user/index.js
Labels: feature

#21 [FEAT] 사용자 계정 페이지 구현
  public/image/app-download-banner.png
  public/image/parents_main_banner.png
  public/index.html
  public/manifest.json
  src/App.js
  src/components/Nav.js
  src/pages/ParentsPages/ VisitSchedule.js
  src/pages/ParentsPages/Request.js
  src/pages/ParentsPages/RequestDetail.js
  src/pages/ParentsPages/Teachers.js
  src/pages/ParentsPages/VisitLog.js
  src/pages/TeacherPages/ ClassSupport.js
  src/pages/TeacherPages/ClassRecommendation.js
  src/pages/TeacherPages/ClassSchedule.js
  src/pages/TeacherPages/TeacherSchedule.js
  src/pages/TeacherPages/TeacherVisit.js
Labels: feature

#23 [FEAT] 유저 관련 api 업데이트
  src/api/user/index.js
Labels: feature

#24 [FEAT] 유저 권한 변경용 api 제작
  src/api/user/index.js
Labels: feature

#25 [FEAT] 사용자 페이지 firebase에서 데이터 가져오기
  src/App.js
  src/components/Nav.js
  src/pages/Parent/ VisitSchedule.js
  src/pages/Parent/Request.js
  src/pages/Parent/RequestDetail.js
  src/pages/Parent/Teachers.js
  src/pages/Parent/VisitLog.js
  src/pages/Teacher/ ClassSupport.js
  src/pages/Teacher/ClassRecommendation.js
  src/pages/Teacher/ClassSchedule.js
  src/pages/Teacher/TeacherSchedule.js
  src/pages/Teacher/TeacherVisit.js
  yarn.lock
Labels: feature

#27 [FEAT] 신용카드 팝업 구현
  src/components/CreditCardPopup/CreditCardPopup.js
  src/components/CreditCardPopup/PopupDom.js
Labels: feature

#32 [FEAT] 신용카드 팝업 구현 #14
  src/components/CreditCardPopup/CreditCardPopup.js
  src/components/CreditCardPopup/PopupDom.js
  src/components/CreditCardPopup/index.js
  src/pages/SignUp/SignUp.js
Labels: feature

#34 [FEAT] Toast 컴포넌트
  src/components/common/ToastPortal/Toast.js
  src/components/common/ToastPortal/ToastPortal.js
  src/components/common/ToastPortal/index.js
Labels: feature

#36 [FEAT] Daum Api를 사용하여 주소검색 기능 구현
  package.json
  src/App.js
  src/components/AddressApi/AddressApi.js
  src/components/AddressApi/index.js
  src/components/Nav/Nav.js
  src/components/Nav/index.js
  src/pages/Parent/index.js
  src/pages/SignUp/SignUp.js
  src/pages/Teacher/index.js
  yarn.lock
Labels: feature

#43 [REFACTOR] 회원가입 성공 실패 처리 시 Toast 컴포넌트 적용
  src/pages/SignUp/SignUp.js
Labels: refactor

#44 [REFACTOR] changeUserRole, adjustRoleForMenu 사용하는곳에서 성공 실패 핸들링가능토록 변경
  src/api/role/index.js
  src/api/user/index.js
Labels: refactor

#51 Feat/37/editnavmenu
  src/components/Nav/Nav.js
Labels: feature

#52 [FEAT] 로그인 성공 시 role에 따른 라우팅 처리
  src/App.js
  src/components/Route/PrivateRoute.js
  src/components/Route/PublicRoute.js
  src/components/Route/index.js
  src/pages/Home/Home.js
  src/pages/Login/Login.js
  src/pages/Parent/Parent.js
  src/pages/Parent/index.js
  src/utils/index.js
  src/utils/storage.js
Labels: feature

#56 [FEAT] Nav 추가기능 구현
  src/components/Nav/Nav.js
  src/pages/Login/Login.js
  src/styles/theme.js
Labels: feature

#48 [REFACTOR] ToastPortal 컴포넌트 스타일 및 리팩토링
  src/components/common/ToastPortal/Toast.js
  src/components/common/ToastPortal/ToastPortal.js
Labels: refactor

#60 [FEAT] 로그아웃시 ToastPortal 띄우기
  src/components/Nav/Nav.js
  yarn.lock
Labels: feature

#64 [Refactor] 파이어베이스 firestore 일일 사용량 초과 방지하기 위한 리팩토링
  public/data/user.json
  src/api/user/index.js
  src/pages/Admin/Search.js
  src/pages/Admin/Table.js
Labels: refactor

#69 [FEAT] Data-Table
  src/components/UserCreate/UserCreate.js
  src/pages/Admin/Modal.js
  src/pages/Admin/Table.js
  src/styles/loginTheme.js
Labels: feature

#74 [REFACTOR} menu 를 가져오는 Api 로직 모듈화, theme에 margin 값 정해서 넣기
  src/components/Nav/Nav.js
  src/pages/Admin/Admin.js
  src/styles/loginTheme.js
  src/styles/theme.js
  src/utils/getRole.js
Labels: refactor

#77 [FEAT] NotFound, Forbidden 컴포넌트 제작 및 적용
  src/App.js
  src/components/Route/PrivateRoute.js
  src/pages/Forbidden/Forbidden.js
  src/pages/Forbidden/index.js
  src/pages/NotFound/NotFound.js
  src/pages/NotFound/index.js
  src/pages/Parent/Parent.js
  src/pages/Teacher/Teacher.js
Labels: feature

#78 [STYLE] menuTheme 생성 및 적용
  public/image/jaranda.image.jpeg
  src/components/Nav/Nav.js
  src/pages/Menu/ClassRecommendation.js
  src/pages/Menu/ClassSchedule.js
  src/pages/Menu/ClassSupport.js
  src/pages/Menu/Request.js
  src/pages/Menu/RequestDetail.js
  src/pages/Menu/TeacherSchedule.js
  src/pages/Menu/TeacherVisit.js
  src/pages/Menu/Teachers.js
  src/pages/Menu/VisitLog.js
  src/pages/Menu/VisitSchedule.js
  src/styles/menuTheme.js
Labels: style

#84 [REFACTOR]forbidden page 화면 nav 안나오게 구현
  src/components/Nav/Nav.js
Labels: refactor

#85 [Docs] 리드미 업데이트 by 이지열
  README.md
Labels: documentation

#89 [REFACTOR] Admin 수정
  src/pages/Admin/Modal.js
Labels: bug, refactor

#97 [FIX] 권한없는 메뉴 진입시 nav 안보이게 하는 로직 추가
  src/components/Nav/Nav.js
Labels: refactor

#100 [REFACTOR] nav 에러 수정
  src/components/Nav/Nav.js
Labels: refactor

#103 [REFACTOR] nav 에러 최종수정완료
  src/App.js
  src/components/Nav/Nav.js
  src/pages/Admin/Admin.js
  src/pages/Admin/AdminRolePageView/AdminRolePageView.js
  src/pages/Login/Login.js
  src/pages/Menu/ClassRecommendation.js
  src/pages/Menu/ClassSchedule.js
  src/pages/Menu/ClassSupport.js
  src/pages/Menu/Request.js
  src/pages/Menu/RequestDetail.js
  src/pages/Menu/TeacherSchedule.js
  src/pages/Menu/TeacherVisit.js
  src/pages/Menu/Teachers.js
  src/pages/Menu/VisitLog.js
  src/pages/Menu/VisitSchedule.js
  src/pages/Parent/Parent.js
  src/pages/SignUp/SignUp.js
  src/pages/Teacher/Teacher.js
Labels: refactor
